version: '3.4'

networks:
  kong-net:
  keycloak-net:

volumes:
  kong-datastore:
  keycloak-datastore:

services:
  kong-db:
    image: postgres:9.6-alpine
    volumes:
      - kong-datastore:/var/lib/postgresql/data
    networks:
      - kong-net
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB:       api-gw
      POSTGRES_USER:     kong
      POSTGRES_PASSWORD: kong

  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6378:6379"
    networks:
      - kong-net

  kong:
    build:
      context: kong/
      dockerfile: Dockerfile
    extra_hosts:
    #  - "keycloak-host:10.18.18.118"
       - "whoami.tmlmobilidade.pt:152.70.161.4"
       - "fe-crm-lite.tmlmobilidade.pt:152.70.161.4"
       - "be-edge-crm.tmlmobilidade.pt:152.70.161.4"
       - "be-edge-pp.tmlmobilidade.pt:152.70.161.4"
       - "fe-pp.tmlmobilidade.pt:152.70.161.4"
    depends_on:
      - kong-db
    networks:
      - kong-net
    ports:
      - "80:8000" # Listener
      - "8081:8001" # Admin API
      - "443:8443" # Listener  (SSL)
      - "444:8444" # Admin API (SSL)
      - "4443:8000" #Port ssl configured
    environment:
      KONG_DATABASE:         postgres
      KONG_PG_HOST:          kong-db
      KONG_PG_PORT:          5432
      KONG_PG_DATABASE:      api-gw
      KONG_PG_USER:          kong
      KONG_PG_PASSWORD:      kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_PLUGINS: bundled,oidc
      KONG_LOG_LEVEL: debug
      KONG_NGINX_HTTP_LUA_SHARED_DICT: introspection 10m

  keycloak-db:
    image: postgres:9.6
    volumes:
      - keycloak-datastore:/var/lib/postgresql/data
    networks:
      - keycloak-net
    ports:
      - "25432:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: jboss/keycloak:4.5.0.Final
    depends_on:
      - keycloak-db
    networks:
      - keycloak-net
    ports:
      - "8180:8080"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-db
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin

  #######################################
  # Konga database prepare
  #######################################
  konga-prepare:
    image: pantsel/konga:latest
    command: "-c prepare -a postgres -u postgresql://kong:${KONG_PG_PASSWORD:-kong}@kong-db:5432/konga"
    networks:
      - kong-net
    restart: on-failure
    depends_on:
      - kong-db

  #######################################
  # Konga: Kong GUI
  #######################################
  konga:
    container_name: konga
    image: pantsel/konga:latest
    restart: always
    depends_on:
    - kong
    networks:
    - kong-net
    ports:
    - "1337:1337" # konga
    environment:
      DB_ADAPTER: postgres
      DB_HOST: kong-db
      DB_USER: kong
      DB_PASSWORD: kong
      DB_PORT: '5432'
      DB_DATABASE: konga_db
      NODE_ENV: development